spring:
  datasource:
    username: root
    password: Lijieqiang@0204
    url: jdbc:mysql://${remote.mysql.ip}:${remote.mysql.port}/databrace?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: ${remote.redis.port}
      host: ${remote.redis.ip}
      database: 1
      password: lijieqiang

mybatis-plus:
  configuration:
    log-impl: com.assign.entrance.base.SQLOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-field: normal
      logic-delete-value: 0
      logic-not-delete-value: 1

remote:
  mysql:
    ip: racacia.love
    port: 3306
  redis:
    ip: racacia.love
    port: 6380