spring:
  datasource:
    username: root
    password: Lijieqiang@0204
    url: jdbc:mysql://li2464r.com:3360/databrace?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6380
      host: apply7.yun.server.com
      database: 0
      password: Lijieqiang@0204
      lettuce:
        pool:
          max-idle: 8
          min-idle: 4
          max-wait: 2000
          max-active: 6

mybatis-plus:
  configuration:
    log-impl: com.racacia.regular.base.SQLOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: normal
      logic-delete-value: 'DISABLE'
      logic-not-delete-value: 'ENABLE'
    banner: off
