spring:
  application:
    name: data-brace
  autoconfigure:
    #排除自动配置的类
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  datasource:
    username: root
    password: Lijieqiang.0204
    url: jdbc:mysql://${remote.ip}:3306/databrace?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: ${remote.ip}
    database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true

server:
  port: 8082

remote:
  ip: dev.ikang.server.com

# rocketMq配置
rocket-mq:
  ip: ${remote.ip}:9876
  group-name: ${spring.application.name}